### ISSUE TITLE
Add type information of Class

### ISSUE THREAD

**Issue by ghost** [dtanzer/jobjectformatter#4]
I would like to know which type is the object.

Eg instead of 
{ id=297e575251d0893e0151d08941a60000, name=test, amount=100.0 }

i would like something like this
Flow { id=297e575251d0893e0151d08941a60000, name=test, amount=100.0 }

**Comment by dtanzer** [comment]
Right now, the simple formatter that is configured by default does not do this. I am planning to add some more formatters in one of the next releases, one of them will definitely produce the format you specified here.

For now, you can use the Json formatter, which already groups the values by declared class, and thus also prints type information. Just configure it during your application startup:

```
final FormattedStringGenerator generator = new FormattedStringGenerator(new JsonObjectStringFormatter());
ObjectFormatter.configureGenerator(generator);
```

But it produces a different output that what you specified in your examples.

**Comment by dtanzer** [comment]
Please update to 0.2.0 - `ConfigurableObjectStringFormatter.UNGROUPED_CURLY_BRACED_OUTPUT_WITH_CLASS_NAME` should produce the output you want:

```
ObjectFormatter.configureGenerator(new FormattedStringGenerator(ConfigurableObjectStringFormatter.UNGROUPED_CURLY_BRACED_OUTPUT_WITH_CLASS_NAME));
System.out.println("ConfigurableObjectStringFormatter.UNGROUPED_CURLY_BRACED_OUTPUT_WITH_CLASS_NAME: "+ObjectFormatter.format(person));
```

Please refer to the updated (yet still incomplete ;) ) readme for details about how to configure a formatter.
